"""Minimal demo protocols used by the orchestration REPL examples and tests.

These were previously defined at module scope in ``orchestration.py``,
which mixed sample data with framework code. They live here so that
importing the orchestration module no longer pulls demo dicts into the
namespace, and so the demo can evolve independently of the framework.

Use::

    from PycroFlow.examples.demo_protocols import protocol
    import PycroFlow.orchestration as por
    po = por.ProtocolOrchestrator(protocol, ...)
"""

protocol_fluid = [
    {'$type': 'inject', 'reservoir_id': 0, 'volume': 500, 'wait_time': 1},
    {'$type': 'incubate', 'duration': 120},
    {'$type': 'inject', 'reservoir_id': 1, 'volume': 500, 'velocity': 600, 'wait_time': 1},
    {'target': 'fluid', '$type': 'signal', 'value': 'fluid round 1 done'},
    {'$type': 'flush', 'flushfactor': 1},
    {'$type': 'wait for signal', 'target': 'img', 'value': 'round 1 done'},
    {'$type': 'inject', 'reservoir_id': 14, 'volume': 500, 'wait_time': 1},
]

protocol_imaging = [
    {'$type': 'wait for signal', 'target': 'fluid', 'value': 'round 1 done'},
    {'$type': 'acquire', 'frames': 100, 't_exp': 100, 'round': 1, 'message': 'R3'},
    {'$type': 'signal', 'value': 'imaging round 1 done'},
]

protocol_illumination = [
    {'$type': 'power', 'value': 1},
    {'$type': 'wait for signal', 'target': 'fluid', 'value': 'round 1 done'},
    {'$type': 'power', 'value': 50},
    {'$type': 'wait for signal', 'target': 'img', 'value': 'round 1 done'},
]

protocol = {
    'fluid': {
        'parameters': {
            'start_velocity': 50,
            'max_velocity': 1000,
            'stop_velocity': 500,
            'mode': 'tubing_stack',  # or 'tubing_flush'
            'extractionfactor': 1,
        },
        'protocol_entries': protocol_fluid,
    },
    'img': {
        'protocol_entries': protocol_imaging,
    },
    'illu': {
        'protocol_entries': protocol_illumination,
    },
}


# Flat protocol (previously hamilton_architecture.protocol): the 'flattened'
# form generated by the upper system from an aggregated Exchange/MERPAINT
# protocol. Kept for reference / legacy callers.
hamilton_flat_protocol = {
    'parameters': {
        'start_velocity': 50,
        'max_velocity': 3000,
        'stop_velocity': 500,
        'mode': 'tubing_stack',  # or 'tubing_flush'
        'extractionfactor': 1,
    },
    'imaging': {
        'frames': 30000,
        't_exp': 100,
    },
    'protocol_entries': [
        {'$type': 'inject', 'reservoir_id': 0, 'volume': 500},
        {'$type': 'incubate', 'duration': 120},
        {'$type': 'inject', 'reservoir_id': 1, 'volume': 500, 'velocity': 600},
        {'$type': 'acquire', 'frames': 10000, 't_exp': 100, 'round': 1},
        {'$type': 'flush', 'flushfactor': 1},
        {'$type': 'await_acquisition'},
        {'$type': 'inject', 'reservoir_id': 14, 'volume': 500},
    ],
}
