"""Hermetic tests for the WP-1 analysis step (analyze_perf).

Proves the analysis path end-to-end on emulator output *and* on hand-crafted
metrics, so the go/no-go logic is exercised deterministically before real
instrument data arrives.
"""

from __future__ import annotations

import importlib.util
import json
import os
import tempfile
import unittest

from PycroFlow.perf.analyze_perf import GO, NO_GO, PENDING, analyze
from PycroFlow.perf.config import PerfConfig
from PycroFlow.perf.harness import run_and_write, write_run_dir

_HAS_MPL = importlib.util.find_spec("matplotlib") is not None

_SAMPLE_RUN = os.path.join(
    os.path.dirname(__file__), "fixtures", "perf", "sample_emulator_run"
)


def _metrics_row(mode, reader, batch, **over):
    row = {
        "mode": mode,
        "reader": reader,
        "batch_size": batch,
        "n_frames": 1000,
        "frame_rate_hz": 100.0,
        "buffer_size": 200,
        "frames_produced": 1000,
        "frames_written": 1000,
        "dropped_count": 0,
        "dropped_fraction": 0.0,
        "occupancy_peak": 2,
        "occupancy_mean": 1.0,
        "throughput_fps": 100.0,
        "duration_s": 10.0,
    }
    row.update(over)
    return row


def _write_synthetic(tmp, mode, metrics, label="wp1"):
    cfg = PerfConfig(mode=mode, batch_sizes=[1], output_dir=tmp, label=label)
    ts = [
        {
            "mode": mode,
            "reader": r["reader"],
            "batch_size": r["batch_size"],
            "sample_index": 0,
            "t_rel_s": 0.0,
            "frame_index": 0,
            "occupancy": r["occupancy_peak"],
        }
        for r in metrics
    ]
    return write_run_dir(
        cfg,
        metrics,
        ts,
        {"backend": mode},
        "2026-01-01T00:00:00+00:00",
        "2026-01-01T00:01:00+00:00",
    )


class TestAnalysisIntegration(unittest.TestCase):
    def test_report_from_emulator_run(self):
        with tempfile.TemporaryDirectory() as tmp:
            cfg = PerfConfig(
                mode="emulator",
                frame_rate_hz=400.0,
                n_frames=200,
                buffer_size=80,
                batch_sizes=[8, 64],
                monitor_interval_s=0.005,
                output_dir=tmp,
            )
            run_dir = run_and_write(cfg)
            out = os.path.join(tmp, "report")
            report = analyze([run_dir], out)

            self.assertTrue(os.path.isfile(os.path.join(out, "report.md")))
            self.assertTrue(os.path.isfile(os.path.join(out, "report.json")))
            with open(os.path.join(out, "report.json")) as fh:
                on_disk = json.load(fh)
            self.assertEqual(
                on_disk["overall_verdict"], report["overall_verdict"]
            )
            # Emulator-only: the mode passes but the overall stays PENDING
            # until the instrument round-trip is analysed.
            self.assertEqual(report["modes"]["emulator"]["verdict"], GO)
            self.assertEqual(report["overall_verdict"], PENDING)
            if _HAS_MPL:
                self.assertTrue(report["plots"])
                for name in report["plots"]:
                    self.assertTrue(os.path.isfile(os.path.join(out, name)))


class TestCommittedSampleRun(unittest.TestCase):
    """Prove the analysis path on a committed emulator run dir.

    This fixture is generated by the emulator harness and committed to the
    repo, so the analysis is reproducible without running the harness (and
    without any instrument) — the analysis path is proven before real data
    arrives.
    """

    def test_analysis_produces_report(self):
        from PycroFlow.perf import schema

        schema.validate_run_dir(_SAMPLE_RUN)
        with tempfile.TemporaryDirectory() as out:
            report = analyze([_SAMPLE_RUN], out)
            self.assertTrue(os.path.isfile(os.path.join(out, "report.md")))
            self.assertTrue(os.path.isfile(os.path.join(out, "report.json")))
            # A clean emulator dry run: the mode passes, overall pends the
            # instrument round-trip.
            self.assertEqual(report["modes"]["emulator"]["verdict"], GO)
            self.assertEqual(report["overall_verdict"], PENDING)


class TestVerdictLogic(unittest.TestCase):
    def test_clean_instrument_is_go(self):
        with tempfile.TemporaryDirectory() as tmp:
            metrics = [
                _metrics_row("instrument", False, 0),
                _metrics_row("instrument", True, 8),
                _metrics_row("instrument", True, 64),
            ]
            run_dir = _write_synthetic(tmp, "instrument", metrics)
            report = analyze([run_dir], os.path.join(tmp, "rep"))
            self.assertEqual(report["modes"]["instrument"]["verdict"], GO)
            self.assertEqual(report["overall_verdict"], GO)

    def test_dropped_frames_force_no_go(self):
        with tempfile.TemporaryDirectory() as tmp:
            metrics = [
                _metrics_row("instrument", False, 0),
                _metrics_row(
                    "instrument",
                    True,
                    128,
                    dropped_count=50,
                    dropped_fraction=0.05,
                    occupancy_peak=180,
                    throughput_fps=70.0,
                ),
            ]
            run_dir = _write_synthetic(tmp, "instrument", metrics)
            report = analyze([run_dir], os.path.join(tmp, "rep"))
            mode = report["modes"]["instrument"]
            self.assertEqual(mode["verdict"], NO_GO)
            self.assertEqual(report["overall_verdict"], NO_GO)
            bad = mode["configs"][0]
            self.assertFalse(bad["dropped_ok"])
            self.assertFalse(bad["throughput_ok"])
            self.assertFalse(bad["occupancy_ok"])

    def test_threshold_override_changes_verdict(self):
        with tempfile.TemporaryDirectory() as tmp:
            metrics = [
                _metrics_row("instrument", False, 0),
                _metrics_row(
                    "instrument",
                    True,
                    64,
                    throughput_fps=90.0,  # 0.90 retention
                ),
            ]
            run_dir = _write_synthetic(tmp, "instrument", metrics)
            # Default min retention 0.95 -> fails.
            r1 = analyze([run_dir], os.path.join(tmp, "r1"))
            self.assertEqual(r1["modes"]["instrument"]["verdict"], NO_GO)
            # Relax to 0.85 -> passes.
            r2 = analyze(
                [run_dir],
                os.path.join(tmp, "r2"),
                thresholds={
                    "max_dropped_fraction": 0.001,
                    "min_throughput_retention": 0.85,
                    "max_occupancy_fraction": 0.5,
                },
            )
            self.assertEqual(r2["modes"]["instrument"]["verdict"], GO)


if __name__ == "__main__":
    unittest.main()
